version: '2.1'

services:
  vproxy:
    build: .
    image: rjlasko/openvpn-proxy:0.1
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    environment:
      HOST_NETWORK_CIDR: "${HOST_NETWORK_CIDR}"
      # TODO: eventually use
      # ADDITIONAL_PORTS: "${ADDITIONAL_PORTS}"
      OVPN_CFG_REGEX: "${OVPN_CFG_REGEX}"
      # TODO: eventually derive & delete these
      NAME_SERVERS: "${NAME_SERVERS}"
      VPN_CONFIG_SRC: "${VPN_CONFIG_SRC}"
      VPN_AUTH_SRC: "${VPN_AUTH_SRC}"
    volumes:
      - "${CONFIG_VOL}:/mnt/config:ro"
      - "~:/mnt/home:ro"
