version: '2.1'

services:
  vprox:
    build: .
    image: rjlasko/openvpn-proxy:0.1
    cap_add:
      - NET_ADMIN
    volumes:
      - "${OPENVPN_CONF}:/mnt/config:ro"
    # devices:
    #   - "/dev/net/tun"
    # dns:
    #   - "8.8.8.8"
    #   - "8.8.4.4"
    